# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'DiscuzQ' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

#（1）#use_frameworks! -> 不使用use_frameworks!则是会生成相应的.a文件(静态链接库)，通过static libraries这个方式来管理pod的代码。
#（2）Linked：libPods-xxx.a包含了其它用pod导入的第三方框架的.a文件。

#（3）use_frameworks! -> 如果使用了use_frameworks!则cocoapods会生成相应的.frameworks文件（动态链接库：实际内容为Header+动态链接库+资源文件），使用dynamic framworks 来取代static libraries方式。
#（4）Linked：Pods_xxx.framework包含了其它用pod导入的第三方框架的.framework文件。
  
#  pod 'UMCommon'    # 必须集成，由原来的UMCCommon变为了UMCommon
#  pod 'UMDevice'    # 必须集成
#  # 社会化分享
#  pod 'UMShare/Social/WeChat'   #集成微信(完整版14.4M)
#  pod 'UMShare/Social/QQ'   #集成QQ/QZone/TIM(完整版7.6M)
#  pod 'UMShare/Social/Sina'   #集成新浪微博(完整版25.3M)
  
  
  pod 'FMDB' # 数据库
  pod 'YYModel' # - 高性能的 iOS JSON 模型框架。
  pod 'YYText' #  — 功能强大的 iOS 富文本框架。
#  pod 'YYKeyboardManager' #  — iOS 键盘监听管理工具。
#  pod 'YYDispatchQueuePool' #  — iOS 全局并发队列管理工具。
#  pod 'YYAsyncLayer' #  — iOS 异步绘制与显示的工具。
  pod 'YYCategories' #  — 功能丰富的 Category 类型工具库。 JKCategories 也很牛逼
  
  pod 'Masonry'
  pod 'MJRefresh', '~> 3.5.0'
#  pod 'XHLaunchAd' # XHPayKit有借鉴意义，建议阅读
  pod 'FLAnimatedImage'
  pod 'DTCoreText', '~> 1.6.25'
  pod 'DTFoundation', '~> 1.7.15'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'MBProgressHUD'
  pod 'ZXPAutoLayout'
  pod 'IQKeyboardManager', '~> 6.5.6'
  pod 'PYSearch' # 搜索控制器
  pod 'ZFPlayer', '~> 4.0.1' # 视频播放器 https://www.jianshu.com/p/c5b71a0c6038
  pod 'ZFPlayer/AVPlayer'
  pod 'ZFPlayer/ControlView'
  
  pod 'TABAnimated', '~> 2.4.7'  # 骨架屏
  
  # 支持SVG格式
  pod 'SDWebImageSVGKitPlugin'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
  
  pod 'WBSUtils' # 默认依赖 SDWebImage YYCache YYWebImage
  pod 'WBSUtils/YYWebImage'
  pod 'WBSUtils/WebViewJsBridge' # WebViewJsBridge
  pod 'WBSUtils/YBImageBrowser' # 图片浏览器 PYPhotoBrowser
  
#  pod 'HXPhotoPicker', '~> 3.1.6'# 图片预览，相册选择器
#  pod 'HXPhotoPicker/SDWebImage', '~> 3.1.6'
#  pod 'GKPhotoBrowser' # 图片浏览器 YBImageBrowser
  pod 'TZImagePickerController', '~> 3.4.3' # 图片选择器
#  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
  
  ## DZQChat 可以借鉴键盘使用
  
  
end
